[package]
name = "generate-random-array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd-json = "0.9.2"
rand = "0.8.5"

[profile.release]
lto = true
codegen-units = 1
target-cpu = "native"
